name: 'Abraham Velázquez Tello'
description: 'Eng @Dropbox | Previously '
logo: '//gravatar.com/avatar/8ed5818f87bbd8bf79e7b36c440e45b9?s=200'
url: 'http://abraham.mx'
sourcecode: 'https://github.com/abrahamvelazquez/abrahamvelazquez.github.io'

baseurl: /
permalink: /:year/:month/:title

exclude: ["node_modules", "gulpfile.js", "package.json", "README.md"]

google_analytics: 'UA-2125211-19'
markdown: redcarpet
highlighter: pygments
paginate: 15

gems: [jekyll-paginate, jekyll-gist]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"

menu:
  -
    title: About
    href: /hola/
  -
    title: Résumé
    href: /resume/
  -
    title: Twitter
    href: https://twitter.com/lunaroja
  -
    title: LinkedIn
    href: https://www.linkedin.com/in/abrahamvelazqueztello
  -
    title: GitHub
    href: https://github.com/abrahamvelazquez
  -
    title: CodePen
    href: http://codepen.io/abrahamvelazquez
  -
    title: Contact
    href: mailto:hola@abraham.mx

prose:
    rooturl: '_posts'
    siteurl: 'http://abraham.mx'
    media: 'assets/images'
